# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: microsoft/setup-msbuild@v1.0.2
      with:
        dotnet-version: 7.0.x
    - name: Build PotableInstaller
      run: dotnet publish ./Installer/Installer.csproj -c Release -r win10-x64
    - name: Rename
      run: Rename-Item -Path ./Installer/bin/x64/Release/net7.0-windows10.0.19041.0/win10-x64 -NewName PotableInstaller
    - name: Build Setup.exe
      run: dotnet publish ./Setup/Setup.csproj -c Release -r win-x64
    - name: Copy
      run: Copy-Item -Path ./Setup/bin/Release/net7.0/win-x64/publish/Setup.exe -Destination ./Installer/bin/x64/Release/net7.0-windows10.0.19041.0/Setup.exe
    - name: Deploy to Build branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./Installer/bin/x64/Release/net7.0-windows10.0.19041.0
        publish_branch: build
